
server {
    listen 1025;
    host 127.0.0.1;
    error_page 404 /errors/404.html;
    error_page 405 400 401;
    client_max_body_size 1M ;

    # =========================
    # 1. STATIC FILES (READ ONLY)
    # =========================
    location / {
        root ./www/html;
        index index.html;
        methods GET;
        autoindex on;
    }

    location /assets/css {
        root ./www/html;
        methods GET;
    }

    # =========================
    # 2. UPLOADS (READ / WRITE / DELETE)
    # =========================
    location /uploads {
        root ./www/html;
        methods GET POST DELETE;
        allow_upload on;
        upload_store ./www/html/uploads;
    }

    # =========================
    # 3. CGI
    # =========================
    location /cgi-bin {
        root ./www/html;
        methods GET POST;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }

    # =========================
    # 4. REDIRECT
    # =========================
    location /old-page {
        return 443 /new-page ;
    }
}
